import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import { ToastContainer } from "react-toastify";
import React from "react";

export const metadata: Metadata = {
  title: "Conry Finance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
    <body className="bg-gray-200 flex">
    <Sidebar />
    <ToastContainer position="top-right"
                    autoClose={5000}
                    hideProgressBar={false}
                    newestOnTop={false}
                    closeOnClick
                    rtl={false}
                    pauseOnFocusLoss
                    draggable
                    pauseOnHover
                    theme="colored" />
    <main className="m-14 w-full">{children}</main>
    </body>
    </html>
  );
}
