import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import Sidebar from "@/components/application/layout/sidebar";
import { ToastContainer } from "react-toastify";
import React from "react";
import Header from "@/components/application/layout/header";

export const metadata: Metadata = {
  title: "Conry Finance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className="bg-gray-200 flex">
        <Sidebar />
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
        <div className="w-full">
          <Header />
          <main className="px-10">{children}</main>
        </div>
      </body>
    </html>
  );
}
