import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import Sidebar from "@/components/application/layout/sidebar";
import { ToastContainer } from "react-toastify";
import React from "react";
import Header from "@/components/application/layout/header";
import RouteBack from "@/components/commons/route-back";

export const metadata: Metadata = {
  title: "Conry Finance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const TC = (
    <ToastContainer
      position="top-right"
      autoClose={5000}
      hideProgressBar={false}
      newestOnTop={false}
      closeOnClick
      rtl={false}
      pauseOnFocusLoss
      draggable
      pauseOnHover
      theme="colored"
    />
  );

  return (
    <html lang="pt-br">
      <body>
        {TC}
        <Header />
        <div className="w-full flex">
          <Sidebar />
          <main className="p-8">
            <RouteBack />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
